version: "3"

services:
  db:
    # platform: linux/x86_64 # M1チップの場合必要
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - /tmp/dockerdir:/etc/mysql/conf.d/
    ports:
      - 3306:3306

  minio:
    image: minio/minio:latest
    command: ["server", "/data", "--console-address", ":9001"] # --console-address オプションの追加
    ports:
      - 9000:9000
      - 9001:9001 # コンソール用のポートフォワード設定追加
    volumes:
      - minio:/data
    # command: server /data
    environment:
      MINIO_ROOT_USER: minio # 元 MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: miniosecret # 元 MINIO_SECRET_KEY

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 minio miniosecret) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/programmer-job-hunting;
      /usr/bin/mc policy download myminio/programmer-job-hunting;
      exit 0;
      "

  api:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./server:/myapp
      - ./server/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3001:3000
    depends_on:
      - db

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - ./client:/usr/src/app
    command: sh -c "cd app && yarn install && yarn start"
    ports:
      - "4000:3000"
  
  # コード補完
  solargraph:
    build: ./server/
    command: bundle exec solargraph socket --host=0.0.0.0 --port=7658
    volumes:
      - ./server:/app
    ports:
      - "8091:7658"

volumes:
  mysql-data:
  minio:
    driver: local
