version: '3'
services:
  deploy:
    image: hashicorp/terraform:0.14.7
    env_file:
      - .env
    volumes:
      - ./terraform/:/code
      - ./terraform-state/:/code/terraform-state
    working_dir: /code
    entrypoint: ash
    tty: true